"""empty message

Revision ID: acacb1908572
Revises: ddf90e37abc3
Create Date: 2025-05-30 18:35:04.897918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acacb1908572'
down_revision = 'ddf90e37abc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_photo', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_photo', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
